#!/usr/bin/env sh
# Usage example:
#   $ ./dadownload
#   $ ./dadownload -p3-4.2

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT  # Clean up the temporary file.

# Compile and download the Lua user scripts.
cd user_logic && \
daluac class.lua effect.lua lamp.lua keymap.lua export.lua >"$tmpfile" && \
dfu-util -a0 -D "$tmpfile" "$@"
