USEMODULE += core_thread
USEMODULE += core_thread_flags
USEMODULE += riotboot_flashwrite
USEMODULE += usbus
USEMODULE += ztimer
USEMODULE += ztimer_msec
DISABLE_MODULE += usbus_hid         # We use our own implementation of usbus_hid,
DISABLE_MODULE += auto_init_usbus   # and do not execute auto_init_usb().

$(shell grep -q 'ENABLE_CDC_ACM = true' $(CONFIG_HPP))
ifeq ($(.SHELLSTATUS),0)
    USEMODULE += stdio_cdc_acm      # Use CDC ACM as default STDIO.
else
    USEMODULE += stdio_null         # Or avoid using stdio and UART at all.
endif

USEMODULE += usbhub                 # for usbhub_thread::signal_usb_suspend/resume()
