USEMODULE += event
USEMODULE += core_thread
USEMODULE += core_thread_flags
USEMODULE += ztimer
USEMODULE += ztimer_msec

USEMODULE += dropalt_adc_get
USEMODULE += dropalt_sr_595
USEMODULE += dropalt_usb2422
USEMODULE += persistent

$(shell grep -q 'ENABLE_RGB_LED = true' $(CONFIG_HPP))
ifeq ($(.SHELLSTATUS),0)
    USEMODULE += dropalt_is31fl3733
endif
