-- Script for the "keymap" module

-- Compile this script and download the generated bytecode to the keyboard using:
-- $ daluac keymap.lua >keymap.bin && dfu-util -a1 -D keymap.bin

-- Note that only the base and package modules are preloaded and registered in the
-- global environment. We need to explicitly "require" for the "fw" module.
local fw = require "fw"

-- Create the module table.
local M = {}

-- It is necessary to manually assign the module table to package.loaded["keymap"],
-- as this module will be loaded using a simplified version of require() provided by
-- the firmware.
package.loaded[...] = M  -- The vararg (...) resolves to the module name "keymap".

-- Beware that any runtime error in this script will cause a crash during firmware
-- boot.
-- package.non_existent_function("nop")  --> run-time error!

-- fw.reboot_to_bootloader()

-- Output the memory usage after the module table has been completely populated.
print("Current Lua memory usage (KB):", collectgarbage("count"))
