# This will automatically download Lua 5.3.6 source files in riot/build/pkg/lua, and
# patch them.
USEPKG += lua               # Lua 5.3.6

# Exclude the parsing modules (lcode, llex, lparser) when building the Lua core.
USEMODULE += lua-contrib_noparser

USEMODULE += log_backup
USEMODULE += persistent
USEMODULE += ps             # for `ps`.
USEMODULE += riotboot_slot  # for using riotboot_slot_*()
USEMODULE += usb            # for usb_thread::send_press/release()
USEMODULE += ztimer
USEMODULE += ztimer_msec

$(shell grep -q 'ENABLE_LUA_REPL = true' $(CONFIG_HPP))
ifeq ($(.SHELLSTATUS),0)
    USEMODULE += lua_repl
endif

FEATURES_REQUIRED += periph_flashpage   # for fw.product_serial()
