# This will automatically download Lua 5.3.4 source files in riot/build/pkg/lua, and
# patch them.
USEPKG += lua                       # Lua 5.3.4

# Exclude the parsing modules (lcode, llex, lparser) when building the Lua core.
USEMODULE += lua-contrib_noparser
