#pragma once

#include "fast_hsv2rgb.h"       // for fast_hsv2rgb_32bit()



struct hsv_t {
    // Hue is in [0, 0x600) rather than [0, 360°), so the high byte (0-5) selects the
    // sextant (RYGCBP) and the low byte (0-255) represents a color in each sextant.
    uint16_t h;
    uint8_t s;
    // Use hsv.v = CIE1931_CURVE[hsv.v] to apply CIE1931_CURVE.
    uint8_t v;

    static constexpr uint16_t COLORS = 0x600;
};



struct rgb_t {
    uint8_t r;
    uint8_t g;
    uint8_t b;

    rgb_t(uint8_t r, uint8_t g, uint8_t b): r(r), g(g), b(b) {}

    rgb_t(const hsv_t& hsv) {
        // References for implementating hsv-to-rgb:
        //  - https://www.vagrearg.org/content/hsvrgb
        //  - https://cs.stackexchange.com/questions/64549/convert-hsv-to-rgb-colors
        //  - https://stackoverflow.com/a/24153899/10451825
        //  - https://programmingfbf7290.tistory.com/entry/%EC%83%89-%EA%B3%B5%EA%B0%843-HSV-HSL
        fast_hsv2rgb_32bit(hsv.h, hsv.s, hsv.v, &r, &g, &b);
    }
};



// Lightness curve using the CIE 1931 lightness formula
// Generated by the python script provided in http://jared.geek.nz/2013/feb/linear-led-pwm
inline constexpr uint8_t CIE1931_CURVE[256] = {
    0,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,   2,   2,   2,   2,   2,
    2,   2,   2,   3,   3,   3,   3,   3,   3,   3,   3,   4,   4,   4,   4,   4,
    4,   4,   5,   5,   5,   5,   5,   6,   6,   6,   6,   6,   7,   7,   7,   7,
    7,   8,   8,   8,   8,   9,   9,   9,   9,  10,  10,  10,  11,  11,  11,  12,
   12,  12,  13,  13,  13,  14,  14,  14,  15,  15,  15,  16,  16,  17,  17,  17,
   18,  18,  19,  19,  20,  20,  21,  21,  22,  22,  23,  23,  24,  24,  25,  25,
   26,  26,  27,  27,  28,  29,  29,  30,  30,  31,  32,  32,  33,  34,  34,  35,
   36,  36,  37,  38,  38,  39,  40,  41,  41,  42,  43,  44,  45,  45,  46,  47,
   48,  49,  50,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
   63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  76,  77,  78,  79,
   80,  81,  83,  84,  85,  86,  88,  89,  90,  91,  93,  94,  95,  97,  98, 100,
  101, 102, 104, 105, 107, 108, 109, 111, 112, 114, 115, 117, 119, 120, 122, 123,
  125, 126, 128, 130, 131, 133, 135, 136, 138, 140, 142, 143, 145, 147, 149, 150,
  152, 154, 156, 158, 160, 162, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
  183, 186, 188, 190, 192, 194, 196, 198, 201, 203, 205, 207, 209, 212, 214, 216,
  219, 221, 223, 226, 228, 231, 233, 235, 238, 240, 243, 245, 248, 250, 253, 255
};
