FEATURES_REQUIRED += periph_wdt

# dropalt_adc_get replaces periph_adc.
ifneq (,$(filter dropalt_adc_get,$(USEMODULE)))
    FEATURES_BLACKLIST += periph_adc
endif

ifneq (,$(filter dropalt_sr_595,$(USEMODULE)))
    FEATURES_REQUIRED += periph_spi
endif

ifneq (,$(filter dropalt_is31fl3733 dropalt_usb2422,$(USEMODULE)))
    FEATURES_REQUIRED += periph_i2c
endif

# ifneq (,$(filter periph_seeprom,$(FEATURES_USED)))
    # This is needed even if we do not access NVM main array since it enables 
    # MCLK_APBBMASK_NVMCTRL. Otherwise access to seeprom registers can cause unintended
    # flash bank swap.
    FEATURES_REQUIRED += periph_flashpage
# endif

ifndef RIOTBOOT_BUILD
USEMODULE += log_backup     # Use log_backup() for LOG_*() on riot functions.
endif

USEMODULE += ztimer
USEMODULE += ztimer_msec
USEMODULE += ztimer_usec
