# Each slot length should be a multiple of 8K (block size for EB command).
NUM_SLOTS   = 2
SLOT0_LEN   = 0x0001C000  # 112K = 256K/2 - 16K (bootloader)
SLOT1_LEN   = 0x00020000  # 128K = 256K/2

PROGRAMMERS_SUPPORTED += dfu-util

include $(RIOTMAKE)/boards/sam0.inc.mk
