# dropalt_adc_get replaces periph_adc.
ifneq (,$(filter dropalt_adc_get,$(USEMODULE)))
    FEATURES_BLACKLIST += periph_adc
endif

ifneq (,$(filter dropalt_sr_595,$(USEMODULE)))
    FEATURES_REQUIRED += periph_spi
endif

ifneq (,$(filter dropalt_is31fl3733 dropalt_usb2422,$(USEMODULE)))
    FEATURES_REQUIRED += periph_i2c
    FEATURES_REQUIRED += periph_dma     # Enable DMA for I2C transfer
endif

ifneq (,$(filter dropalt_seeprom,$(USEMODULE)))
    # The periph_flashpage module is needed even if the NVM main array is not accessed,
    # because it enables MCLK_APBBMASK_NVMCTRL. Without it, accessing the SEEPROM
    # registers might inadvertently trigger a flash bank swap.
    FEATURES_REQUIRED += periph_flashpage
endif

ifneq (,$(filter dropalt_matrix,$(USEMODULE)))
    FEATURES_REQUIRED += periph_gpio_irq   # for gpio_init_int()
endif

ifndef RIOTBOOT_BUILD
FEATURES_REQUIRED += periph_wdt
USEMODULE += log_backup             # Use log_backup() for LOG_*() on riot functions.
USEMODULE += ps                     # Show `ps` on a hard fault and assert failure.
endif

USEMODULE += riotboot_reset         # Reboot to bootloader on core_panic().
                                    # Will also include `+= usb_board_reset`.
USEMODULE += ztimer
USEMODULE += ztimer_msec
USEMODULE += ztimer_usec
