MODULE = board

SRC := board.c

# Each 'xxx.c' file in this directory will constitute a separate submodule named
# 'dropalt_xxx'.
BASE_MODULE := dropalt
SUBMODULES = 1

include $(RIOTBASE)/Makefile.base
